// The four models in the Sahara range. The Mirage and X-Master each ship with
// two variants the visitor can switch between on the detail page without a
// route change. Dune and Horizon stay single-variant; the ModelPage falls back
// to the top-level fields when `variants` is absent.

// Sahara bodies come in six lengths. Most variants are available in all six;
// the X-Master Slide-Out is the exception (single 22'6 chassis). Per-size
// blueprints are looked up via `floorPlansBySize`; missing sizes fall back to
// the variant's default `floorPlan`.
export const DEFAULT_SIZES = ['16-6', '17-6', '18-6', '19-6', '20-6', '22-6']
export const SIZE_LABELS = {
  '16-6': "16'6",
  '17-6': "17'6",
  '18-6': "18'6",
  '19-6': "19'6",
  '20-6': "20'6",
  '21-6': "21'6",
  '22-6': "22'6",
}

export const models = [
  {
    slug: 'x-master',
    name: 'Sahara X-Master',
    type: 'Off-Road',
    order: 1,
    tagline: 'Explore the wild without leaving comfort behind.',
    description:
      'The X-Master is your ultimate companion for off-grid adventures. Matte-black body, checker-plate armor, tandem off-road suspension and a fully stocked electrical bay mean you can head well past the blacktop and stay out for weeks. Pick between the compact Standard 196 single-body tourer or the 226 Slide-Out — where a roadside wall extrudes at camp to double the living space.',
    heroImage: '/images/hero/hero-xmaster.png',
    highlights: ['Toilet', 'Shower', 'Laundry', 'Kitchenette', 'Off-Grid'],
    ctaLabel: 'Enquire about the X-Master',
    // Full manufacturer build sheet — shared across both X-Master variants.
    technicalSpecs: [
      {
        id: 'chassis',
        label: 'Chassis',
        rows: [
          { label: 'Axle', value: 'Single or Tandem Axle' },
          { label: 'A-Frame Configuration', value: '6" Reinforced A-Frame Extended Drawbar' },
          { label: 'Main Chassis Frame', value: '3.2mm Box Australian Steel Chassis' },
          { label: 'Raiser', value: '4"' },
          { label: 'Tyres', value: '16" Alloy with Mud Terrain Tyres' },
          { label: 'Brakes', value: '12"' },
          { label: 'Suspension', value: 'Independent Coil and Shock' },
          { label: 'Heavy Duty Rear Bumper Bar', value: '3 Arm with Spare Wheel' },
          { label: 'Tool Box', value: 'Centre Gas Bottle Tool Box with Dual Slides' },
          { label: '2 x Jerry Can Holders', value: 'Included' },
          { label: 'Generator Slide', value: 'Included' },
          { label: 'Stone Guard', value: 'Included' },
          { label: 'Quick Drop Stands', value: 'Included' },
          { label: 'Trailer Coupling', value: 'DO-35 Off Road Coupling' },
        ],
      },
      {
        id: 'solar-power',
        label: 'Solar & Power',
        rows: [
          { label: '200w Solar Panel/s', value: '4' },
          { label: '50 Amp MPPT Solar Regulator', value: '2' },
          { label: 'Battery — 200 Amp Lithium Battery On Chassis', value: '2' },
          { label: 'Victron Electrical System', value: 'Included' },
          { label: 'Electrical Control Panel', value: 'Victron Cerbo GX — Touch 50 Screen' },
          { label: 'Solar Inverter', value: 'Victron 3000VA Multiplus II Inverter 120 Amp' },
          { label: 'DC Charger', value: '50 Amp DC-DC Charger' },
        ],
      },
      {
        id: 'electrical',
        label: 'Electrical',
        rows: [
          { label: 'HD TV Antenna', value: 'Included' },
          { label: 'External TV Outlet', value: 'Included' },
          { label: 'LED TV', value: '24"' },
          { label: 'Sound System', value: 'CD/DVD Sound System' },
          { label: 'LED Strip Lighting Throughout', value: 'Included' },
          { label: 'LED/Orange Bug Annexe Lights', value: '2' },
          { label: 'Working Lamps Front and Rear', value: 'Included' },
          { label: 'Off-side Annexe Light', value: 'Included' },
          { label: '12 Volt Fans On Roof Behind Hatch', value: '2' },
          { label: '12 Volt Fans on each Bunk on Family Vans', value: 'Included' },
          { label: 'Reverse Camera incl. Car Kit', value: 'Included' },
        ],
      },
      {
        id: 'plumbing',
        label: 'Plumbing',
        rows: [
          { label: '9KG Gas Bottles', value: '2' },
          { label: '95Ltr Water Tanks', value: '2' },
          { label: '100 Ltr Grey Water Tanks', value: '1' },
          { label: 'Filtered Drinking Water Tap', value: 'Included' },
          { label: 'One Piece Shower', value: 'Included' },
          { label: 'Water Saving Shower Head', value: 'Included' },
          { label: 'Ceramic Fresh Flush Toilet', value: 'Included' },
          { label: 'Tap on A-Frame', value: 'Included' },
          { label: 'External Gas Bayonet', value: 'Included' },
          { label: 'External Shower Hot and Cold', value: 'Included' },
          { label: 'Mains Pressure Inlet', value: 'Included' },
          { label: 'Gas/Electric Hot Water System', value: 'Included' },
        ],
      },
      {
        id: 'appliances',
        label: 'Appliances',
        rows: [
          { label: 'Standard Fridge', value: '224L Compressor Fridge' },
          { label: 'Cooking', value: 'Stove, Mini Grill & 3 in 1 Cooker' },
          { label: '12 Volt Rangehood', value: 'Included' },
          { label: 'Washing Machine', value: 'Included' },
          { label: 'Low Profile Air Conditioner', value: 'Included' },
        ],
      },
      {
        id: 'external',
        label: 'External',
        rows: [
          { label: '3mm Aluminium Smooth Composite Panel', value: 'Included' },
          { label: 'High Checker Plate Sides', value: '600mm X-Plate' },
          { label: 'Checker plate Front and Rear', value: 'Included' },
          { label: 'Dust Reduction System', value: 'Dometic Dust Reduction System' },
          { label: 'Double Glazed Windows with Flat Blinds', value: 'Included' },
          { label: 'Large Tunnel Boot', value: 'Included' },
          { label: 'External Entertainment Hatch', value: 'Included' },
          { label: 'Tri-Lock Main Door', value: 'Included' },
          { label: 'Aluminium Picnic Table', value: 'Included' },
          { label: 'Aluminium Cased LED Annexe Lights', value: 'Included' },
          { label: 'Sky Light with Block-out and Fly Screens', value: '2' },
          { label: 'Roll Out Awning', value: 'Included' },
          { label: 'Awning Centre Cradle', value: 'Included' },
          { label: 'Custom Edge Capping', value: 'Included' },
          { label: 'Entrance Step', value: 'Pullout Double Step' },
        ],
      },
      {
        id: 'internal',
        label: 'Internal',
        rows: [
          { label: 'Seating', value: 'Café or L-Shape' },
          { label: 'Queen Bed and Optional Single Bed', value: 'Included' },
          { label: '2, 3 or 4 Bunk Options (Family Vans)', value: 'Included' },
          { label: 'Full Height Laminate Benchtops', value: 'Included' },
          { label: 'Waterfall Square Edge Benchtops (Model Depending)', value: 'Included' },
          { label: 'LED Wide Area Roof Lighting', value: 'Included' },
          { label: 'LED Reading Lamps', value: 'Included' },
          { label: 'Piano Hinges to all Cupboards', value: 'Included' },
          { label: 'Soft Close Runners on Drawers', value: 'Included' },
          { label: 'Tapware', value: 'Choice: Chrome or Black' },
          { label: 'Internal Roof Height', value: '6\'7"' },
          { label: 'LED Handle at Entry', value: 'Included' },
          { label: 'Magazine Pouch — Layout Depending', value: 'Included' },
          { label: 'Fortitude Embroidery', value: 'Included' },
        ],
      },
    ],
    variants: [
      {
        key: 'standard',
        label: 'Standard',
        shortLabel: 'Standard',
        badge: 'X-Master 196',
        blurb: 'Compact single-body off-road tourer — tandem axle, full ensuite, designed to go anywhere.',
        blueprint: '/images/blueprints/x-master-standard.webp',
        floorPlan: '/images/blueprints/x-master-standard-floorplan.png',
        sizes: DEFAULT_SIZES,
        floorPlansBySize: {
          '19-6': '/images/blueprints/x-master-standard-floorplan.png',
        },
        description:
          'The X-Master 196 Standard is the tight, trail-ready version of the range. A single-body off-road tourer on a tandem off-road chassis, with every serious go-anywhere feature you\'d expect — DO35-style hitch, stone-guard nose, checker-plate armor along the underbody, reinforced coil suspension and a full external electrical bay. Inside it\'s every bit as finished as the on-road vans: cafe dinette, 4-burner cooktop with oven, full rear ensuite with laundry, and a private queen bed at the back.',
        features: [
          'Matte-black body with deep-red and burgundy graphics',
          'Tandem off-road suspension with coil + shocks',
          'DO35-style off-road hitch and stone-guard nose cone',
          'Full checker-plate armor along the underbody',
          'External electrical bay — Projecta PM335C DC-DC charger, TechWorld fuse board',
          'Dometic cassette air-conditioner and Sirocco ceiling fan',
          'Cafe-style L-dinette with fixed table — converts for an extra sleep',
          'Full galley — 4-burner gas cooktop with oven, stainless sink, stone benchtop',
          'Rear private queen bedroom with wrap-around overhead storage',
          'Full ensuite with separate shower, cassette toilet and marble-look vanity',
          'External slide-out kitchen shelf for cooking in camp',
          '"Leak Tight RVs Tested" certified — water-sealed for long trips',
        ],
        specs: {
          sleeps: 'Up to 6',
          length: 'TBC',
          tare: 'TBC',
          atm: 'TBC',
          suspension: 'Heavy-duty independent coil',
          water: 'TBC',
          warranty: 'TBC',
        },
        gallery: {
          exterior: [
            { src: '/images/models/x-master-standard/exterior-01.jpg', caption: 'Rear-quarter view — "X-Master 196" badge, tandem off-road suspension, low-profile stance.' },
            { src: '/images/models/x-master-standard/exterior-02.jpg', caption: 'Rear door panel — Sahara crest, LED tail cluster, full checker-plate underbody.' },
            { src: '/images/models/x-master-standard/exterior-03.jpg', caption: 'Roadside profile — awning rail, large tinted windows, burgundy accent graphics.' },
            { src: '/images/models/x-master-standard/exterior-04.jpg', caption: 'External slide-out kitchen shelf deployed — stainless sink and gas cooktop for cooking in camp.' },
            { src: '/images/models/x-master-standard/exterior-05.jpg', caption: 'Awning-side view — entry door, external speakers and reverse-camera housing.' },
            { src: '/images/models/x-master-standard/exterior-06.jpg', caption: 'Front-quarter — stone-guard nose, jerry-can mounts and external BBQ shelf.' },
            { src: '/images/models/x-master-standard/exterior-07.jpg', caption: 'Kitchen-shelf wide view — slide-out galley fully extended with the BBQ cover in place.' },
            { src: '/images/models/x-master-standard/exterior-08.jpg', caption: 'Off-road hitch and drawbar — DO35-style coupling with dropped spare-wheel mount.' },
            { src: '/images/models/x-master-standard/exterior-09.jpg', caption: 'Electrical bay — Projecta PM335C DC-DC charger, TechWorld fuse board, hot-water and gas switches.' },
          ],
          interior: [
            { src: '/images/models/x-master-standard/interior-01.jpg', caption: 'Galley detail — gloss light-grey uppers, dark gloss drawers, stone benchtop with under-bench oven.' },
            { src: '/images/models/x-master-standard/interior-02.jpg', caption: 'Cafe dinette looking back to the bedroom — Sahara-branded leather-look cushions and a stone-look tabletop.' },
            { src: '/images/models/x-master-standard/interior-03.jpg', caption: 'Rear queen bedroom — padded headboard, overhead storage, bedside shelves with reading lights.' },
            { src: '/images/models/x-master-standard/interior-04.jpg', caption: 'Looking through from the bed — galley left, cafe dinette right, entry door to the rear.' },
            { src: '/images/models/x-master-standard/interior-05.jpg', caption: 'Galley looking toward the bedroom — 4-burner cooktop with oven, large stainless sink, skylight overhead.' },
            { src: '/images/models/x-master-standard/interior-06.jpg', caption: 'Bedroom from the galley — privacy door to the ensuite, external window, quilted mattress.' },
            { src: '/images/models/x-master-standard/interior-07.jpg', caption: 'Ensuite — cassette toilet, marble-look vanity with black vessel sink and drawer storage.' },
            { src: '/images/models/x-master-standard/interior-08.jpg', caption: 'Ensuite wide — stone-look wall tiles, overhead mirror cabinets and a privacy window.' },
            { src: '/images/models/x-master-standard/interior-09.jpg', caption: 'Separate shower stall — matte-black slide rail, chrome riser and low-step shower tray.' },
            { src: '/images/models/x-master-standard/interior-10.jpg', caption: 'Shower looking in — frosted glass privacy panel with a matching matte-black frame.' },
            { src: '/images/models/x-master-standard/interior-11.jpg', caption: 'Dinette from the rear — fridge/microwave tower, Sahara-branded upholstery, panoramic window.' },
            { src: '/images/models/x-master-standard/interior-12.jpg', caption: 'Ensuite rear view — mirror-fronted upper cabinetry and marble-look benchtop with vessel sink.' },
            { src: '/images/models/x-master-standard/interior-13.jpg', caption: 'Fridge / microwave column with entry door — black appliances against bright white cabinetry.' },
            { src: '/images/models/x-master-standard/interior-14.jpg', caption: 'Kitchen rear view — full bench, drawer stack, window over the sink.' },
            { src: '/images/models/x-master-standard/interior-15.jpg', caption: 'Galley wide — gloss uppers, 4-burner cooktop with oven, black sink and mixer tap.' },
          ],
        },
      },
      {
        key: 'slideout',
        label: 'Slide-Out',
        shortLabel: 'Slide-Out',
        badge: 'X-Master 226',
        blurb: 'Extended 226 body with a side wall that extrudes at camp — markedly wider inside when the slide is deployed.',
        blueprint: '/images/blueprints/x-master-slideout.webp',
        floorPlan: '/images/blueprints/x-master-slideout-floorplan.png',
        sizes: ['22-6'],
        floorPlansBySize: {
          '22-6': '/images/blueprints/x-master-slideout-floorplan.png',
        },
        description:
          'The X-Master 226 Slide-Out is the room-to-breathe version of the same off-road tourer. A roadside wall section extrudes at camp to markedly widen the living area, more floor space for dressing, and the galley no longer sharing a walkway. Built around a hybrid PVC-ply frame, composite honeycomb floor and one-piece moulded roof — the kind of construction that lets it carry 840W of solar, 400Ah of lithium and a full diesel-heating loop without weight penalty.',
        features: [
          'Hybrid frame with full PVC ply walls, one-piece moulded roof and composite honeycomb floor',
          'Allytech awning windows throughout — including a 600mm slider over the dinette',
          'Extending slide-out wall — markedly wider interior when deployed',
          'Off-road suspension on 245/75/R15 rims and tyres',
          'DO35 coupling with 2-metre extended drawbar, stone guard and mesh-on-frame protection',
          '900mm black chequer-plate skirt and twin slide-out toolboxes',
          '4x 210W solar panels (840W) with Projecta regulator and charging system',
          '2x 200Ah lithium batteries (400Ah) with a 3000W iTech inverter and dual kitchen powerpoints',
          'AU Focus diesel heater and 2x freshwater tanks plus a grey-water tank for off-grid stays',
          'Galley with 3-in-one microwave, mini grill, compressor fridge, stainless sink, Carafan rangehood and soft-close drawers',
          'Front private queen bedroom with full-height robes either side of a 32" TV',
          'Full ensuite with separate shower, cassette toilet, top-load washing machine and linen drawer',
          'All-black tapware, round basin, shower frame and glass throughout the ensuite',
          'Black reading lights, white overhead strip lighting, orange bug lights and 12V fans in the bed area',
          'External slide-out BBQ, fold-out picnic table and exterior TV box for camp setup',
        ],
        inclusions: {
          title: '22\'6" Off-Road X-Master Slide-Out',
          included: [
            'Rolled benchtop',
            'Electrical certificate',
            'WA off-road pack',
            'Black pack upgrade (sinks + fittings)',
          ],
          addOns: [
            '2 x 12V fans',
            'Woodbox',
            'TV box',
            'Xplate 900mm high',
            '2 x 200Ah lithium battery',
            '3000W iTech inverter',
            '2x additional solar + regulator',
            'Carafan',
            'AU Focus diesel heater',
            'Stone guard',
            '2m drawbar extension + toolbox 2 slider',
            'DO35 coupling',
            '3-in-1 microwave airfryer',
            'Swift slide-out BBQ',
            'Off-road suspension',
            'Mesh on a frame',
          ],
        },
        specs: {
          sleeps: 'Up to 6',
          length: 'TBC',
          tare: 'TBC',
          atm: 'TBC',
          suspension: 'Heavy-duty independent coil',
          water: 'TBC',
          warranty: 'TBC',
        },
        gallery: {
          exterior: [
            { src: '/images/models/x-master-slideout/exterior-01.jpg', caption: 'Roadside profile — "X-Master 226" badge, full matte-black finish with silver-grey accent panels.' },
            { src: '/images/models/x-master-slideout/exterior-02.jpg', caption: 'Off-side rear quarter — tandem off-road wheels, full checker-plate armor, awning rail.' },
            { src: '/images/models/x-master-slideout/exterior-03.jpg', caption: 'Roadside front view — entry door, pull-out step, external storage hatches.' },
            { src: '/images/models/x-master-slideout/exterior-04.jpg', caption: 'Rear view — Sahara crest lightbox, LED tail cluster, full-width reinforced bumper.' },
            { src: '/images/models/x-master-slideout/exterior-05.jpg', caption: 'Front-quarter at the yard — twin gas-bottle hitch, drawbar and stone-guard nose.' },
            { src: '/images/models/x-master-slideout/exterior-06.jpg', caption: 'Parked alongside the Sahara blue workshop van — the 226 silhouette in context.' },
          ],
          interior: [
            { src: '/images/models/x-master-slideout/interior-01.jpg', caption: 'Mid-ship ensuite — cassette toilet, drawer storage, marble-look vanity with vessel sink.' },
            { src: '/images/models/x-master-slideout/interior-02.jpg', caption: 'Ensuite wide — full-height mirror, matte-black mixer tap, privacy window.' },
            { src: '/images/models/x-master-slideout/interior-03.jpg', caption: 'Separate shower stall — chrome slide rail, wet-wall panels, ambient overhead light.' },
            { src: '/images/models/x-master-slideout/interior-04.jpg', caption: 'Wardrobe / cabinet column beside the bed — plenty of hanging space and deep drawer storage.' },
            { src: '/images/models/x-master-slideout/interior-05.jpg', caption: 'Front queen bedroom — mattress with the storage base lifted, bedside cabinets to either side.' },
            { src: '/images/models/x-master-slideout/interior-06.jpg', caption: 'U-lounge with the slide deployed — big enough for four adults plus a slide-in table.' },
            { src: '/images/models/x-master-slideout/interior-07.jpg', caption: 'Deployed lounge wide — wrap-around cushions, extra skylight and natural light from both sides.' },
            { src: '/images/models/x-master-slideout/interior-08.jpg', caption: 'Bedroom from the foot of the bed — extra headroom through the pop-top skylight.' },
            { src: '/images/models/x-master-slideout/interior-09.jpg', caption: 'Galley detail — matte-grey uppers, dark gloss lowers, stone benchtop with under-bench oven.' },
            { src: '/images/models/x-master-slideout/interior-10.jpg', caption: 'Lounge looking back to the bedroom — slide-out wall visible on the right, galley on the left.' },
            { src: '/images/models/x-master-slideout/interior-11.jpg', caption: 'Galley looking toward the bedroom — long bench run, big sink, oven and cooktop.' },
            { src: '/images/models/x-master-slideout/interior-12.jpg', caption: 'Lounge corner — Sahara-branded leather-look cushions, slide-in table, panoramic window.' },
            { src: '/images/models/x-master-slideout/interior-13.jpg', caption: 'Ensuite looking in — vanity, toilet and shower aligned along a single wall for easy use.' },
            { src: '/images/models/x-master-slideout/interior-14.jpg', caption: 'Bedroom showing the ensuite doorway — mid-ship placement keeps the walkway short.' },
            { src: '/images/models/x-master-slideout/interior-15.jpg', caption: 'Kitchen from the lounge — fridge/microwave tower, entry door, wood-look flooring.' },
            { src: '/images/models/x-master-slideout/interior-16.jpg', caption: 'Bedroom from the hall — privacy sliding door, large wall mirror and built-in wardrobe.' },
            { src: '/images/models/x-master-slideout/interior-17.jpg', caption: 'Ensuite detail — marble-look vanity, stone-look wall tiles, chrome and matte-black fittings.' },
            { src: '/images/models/x-master-slideout/interior-18.jpg', caption: 'Bedroom under the pop-top — oversized skylight floods the space with natural light.' },
            { src: '/images/models/x-master-slideout/interior-19.jpg', caption: 'Vanity close-up — vessel sink, mixer tap, drawer stack and shelving to either side.' },
          ],
        },
      },
    ],
  },
  {
    slug: 'mirage',
    name: 'Sahara Mirage',
    type: 'On-Road',
    order: 2,
    tagline: 'Comfort and convenience on the open road.',
    description:
      'The Mirage is designed for travellers who value comfort and ease above all. A sleek, streamlined build makes it effortless to tow, while the fully equipped kitchenette and spacious interior feel like home long before you\'ve unpacked. Four floor plans to choose from — two lounge-led layouts (cafe-style dinette or twin recliners) and two compact bedroom-led layouts (rear queen bed or twin singles) — so the Mirage can match the way you actually travel.',
    heroImage: '/images/hero/hero-mirage-outback.png',
    highlights: ['Toilet', 'Shower', 'Laundry', 'Kitchenette'],
    ctaLabel: 'Enquire about the Mirage',
    // Full manufacturer build sheet — shared across all Mirage variants.
    technicalSpecs: [
      {
        id: 'chassis',
        label: 'Chassis',
        rows: [
          { label: 'Axle', value: 'Single or Tandem Axle' },
          { label: 'A-Frame Configuration', value: '6" Reinforced A-Frame Extended Drawbar' },
          { label: 'Main Chassis Frame', value: '3.2mm Box Australian Steel Chassis' },
          { label: 'Tyres', value: '16" Alloy with All Terrain Tyres' },
          { label: 'Brakes', value: '12"' },
          { label: 'Suspension', value: 'Independent Coil and Shock' },
          { label: 'Heavy Duty Rear Bumper Bar', value: '3 Arm with Spare Wheel' },
          { label: 'Tool Box', value: 'Large Flat Top Tool Box' },
          { label: 'Generator Slide', value: 'Included' },
          { label: 'Quick Drop Stands', value: 'Included' },
          { label: 'Trailer Coupling', value: 'DO-35 Off Road Coupling' },
        ],
      },
      {
        id: 'solar-power',
        label: 'Solar & Power',
        rows: [
          { label: '200w Solar Panel/s', value: '3' },
          { label: '30 Amp MPPT Solar Regulator', value: '1' },
          { label: 'Battery — 300 Amp Lithium Battery On Chassis', value: '1' },
          { label: 'Victron Electrical System', value: 'Included' },
          { label: 'Electrical Control Panel', value: 'Victron Cerbo GX — Touch 50 Screen' },
          { label: 'Solar Inverter', value: 'Victron 3000VA Multiplus II Inverter 120 Amp' },
          { label: 'DC Charger', value: '30 Amp DC-DC Charger' },
        ],
      },
      {
        id: 'electrical',
        label: 'Electrical',
        rows: [
          { label: 'HD TV Antenna', value: 'Included' },
          { label: 'External TV Outlet', value: 'Included' },
          { label: 'LED TV', value: '24"' },
          { label: 'Sound System', value: 'CD/DVD Sound System' },
          { label: 'LED Strip Lighting Throughout', value: 'Included' },
          { label: 'LED/Orange Bug Annexe Lights', value: '2' },
          { label: '12 Volt Fans On Roof Behind Hatch', value: '2' },
          { label: 'Reverse Camera incl. Car Kit', value: 'Included' },
        ],
      },
      {
        id: 'plumbing',
        label: 'Plumbing',
        rows: [
          { label: '9KG Gas Bottles', value: '2' },
          { label: '95Ltr Water Tanks', value: '2' },
          { label: '100 Ltr Grey Water Tanks', value: '1' },
          { label: 'Filtered Drinking Water Tap', value: 'Included' },
          { label: 'One Piece Shower', value: 'Included' },
          { label: 'Water Saving Shower Head', value: 'Included' },
          { label: 'Ceramic Fresh Flush Toilet', value: 'Included' },
          { label: 'Tap on A-Frame', value: 'Included' },
          { label: 'External Gas Bayonet', value: 'Included' },
          { label: 'Mains Pressure Inlet', value: 'Included' },
          { label: 'Gas/Electric Hot Water System', value: 'Included' },
        ],
      },
      {
        id: 'appliances',
        label: 'Appliances',
        rows: [
          { label: 'Standard Fridge', value: '188L Tropical 3-Way Fridge/Freezer' },
          { label: 'Cooking', value: 'Stove, Full Oven & Grill' },
          { label: '12 Volt Rangehood', value: 'Included' },
          { label: 'Microwave', value: 'Included' },
          { label: 'Washing Machine', value: 'Included' },
          { label: 'Low Profile Air Conditioner', value: 'Included' },
        ],
      },
      {
        id: 'external',
        label: 'External',
        rows: [
          { label: '3mm Aluminium Smooth Composite Panel', value: 'Included' },
          { label: 'High Checker Plate Sides', value: '600mm Checker Plate' },
          { label: 'Checker plate Front and Rear', value: 'Included' },
          { label: 'Double Glazed Windows with Flat Blinds', value: 'Included' },
          { label: 'Large Tunnel Boot', value: 'Included' },
          { label: 'External Entertainment Hatch', value: 'Included' },
          { label: 'Tri-Lock Main Door', value: 'Included' },
          { label: 'Aluminium Picnic Table', value: 'Included' },
          { label: 'Aluminium Cased LED Annexe Lights', value: 'Included' },
          { label: 'Sky Light with Block-out and Fly Screens', value: '2' },
          { label: 'Roll Out Awning', value: 'Included' },
          { label: 'Awning Centre Cradle', value: 'Included' },
          { label: 'Entrance Step', value: 'Manual Single Step' },
        ],
      },
      {
        id: 'internal',
        label: 'Internal',
        rows: [
          { label: 'Seating', value: 'Café or L-Shape' },
          { label: 'Queen Bed and Optional Single Bed', value: 'Included' },
          { label: '2, 3 or 4 Bunk Options (Family Vans)', value: 'Included' },
          { label: 'Full Height Laminate Benchtops', value: 'Included' },
          { label: 'Waterfall Square Edge Benchtops (Model Depending)', value: 'Included' },
          { label: 'LED Wide Area Roof Lighting', value: 'Included' },
          { label: 'LED Reading Lamps', value: 'Included' },
          { label: 'Piano Hinges to all Cupboards', value: 'Included' },
          { label: 'Soft Close Runners on Drawers', value: 'Included' },
          { label: 'Tapware', value: 'Choice: Chrome or Black' },
          { label: 'Internal Roof Height', value: '6\'7"' },
          { label: 'Magazine Pouch — Layout Depending', value: 'Included' },
          { label: 'Fortitude Embroidery', value: 'Included' },
        ],
      },
    ],
    variants: [
      {
        key: 'cafe',
        label: 'Cafe Style',
        shortLabel: 'Cafe',
        badge: 'Mirage · Cafe Lounge',
        blurb: 'Fixed L-shaped cafe dinette with pedestal table — seats the whole family for meals and folds out for an extra bed.',
        blueprint: '/images/blueprints/mirage-cafe.webp',
        sizes: DEFAULT_SIZES,
        floorPlansBySize: {},
        description:
          'The Cafe-style Mirage keeps things classic. A fixed L-shaped dinette with a solid pedestal table gives you a proper spot for meals, laptops, card games and long cups of tea on a rainy afternoon. Gloss white upper cabinetry, stone-look benchtops and a hex-tile ensuite give the whole space a bright, premium feel — while the rear queen bedroom stays tucked away for an easy night.',
        features: [
          'Fixed L-shaped cafe dinette with solid pedestal table',
          'Converts into an extra double bed for guests',
          'Gloss white upper cabinetry and dark gloss lower drawers',
          'Full kitchen — 4-burner cooktop with oven, stainless sink, stone-look bench',
          'Rear private queen bed with wrap-around storage',
          'Full ensuite with separate shower, cassette toilet and vanity',
          'Hexagon-tile ensuite floor with marble-look vanity top',
          'Dometic cassette air-conditioner and Sirocco ceiling fan',
          'Large panoramic windows — bright, light-filled interior',
        ],
        specs: {
          sleeps: 'Up to 6',
          length: 'TBC',
          tare: 'TBC',
          atm: 'TBC',
          suspension: 'Standard independent',
          water: 'TBC',
          warranty: 'TBC',
        },
        gallery: {
          exterior: [
            {
              src: '/images/models/mirage-cafe/exterior-01.jpg',
              caption: 'Mirage 206 front-quarter — twin gas-bottle hitch, off-road-ready drawbar, white body with charcoal and green graphics.',
            },
            {
              src: '/images/models/mirage-cafe/exterior-02.jpg',
              caption: 'Rear view — reflective tail strip, spare wheel mount, full checker-plate stone guard along the underbody.',
            },
            {
              src: '/images/models/mirage-cafe/exterior-03.jpg',
              caption: 'Mirage 186 front — twin gas bottles and off-road drawbar, Sahara Caravans branding in green and charcoal.',
            },
          ],
          interior: [
            { src: '/images/models/mirage-cafe/interior-01.jpg', caption: 'Ensuite corner — gloss white cabinetry, hex-tile floor and the edge of the separate shower stall.' },
            { src: '/images/models/mirage-cafe/interior-02.jpg', caption: 'Cafe dinette looking back to the bedroom — bench seats with a fixed stone-look table and a skylight over the lounge.' },
            { src: '/images/models/mirage-cafe/interior-03.jpg', caption: 'Separate shower stall — chrome hand-held, slide rail and slip-resistant base set in bright white wet-wall panels.' },
            { src: '/images/models/mirage-cafe/interior-04.jpg', caption: 'Dinette from the galley side — L-lounge with fixed table, fridge and microwave column on the right, skylight overhead.' },
            { src: '/images/models/mirage-cafe/interior-05.jpg', caption: 'Cafe dinette from the kitchen — cushioned bench seats, fixed table, fridge column and entry door alongside.' },
            { src: '/images/models/mirage-cafe/interior-06.jpg', caption: 'Dinette wide angle — cafe seating on the right, galley on the left, skylight drawing daylight into the main living.' },
            { src: '/images/models/mirage-cafe/interior-07.jpg', caption: 'Galley wide — gloss white uppers, grey lower drawers, stone benchtop with under-bench oven and stainless sink.' },
            { src: '/images/models/mirage-cafe/interior-08.jpg', caption: 'Ensuite — cassette toilet, front-loading washer column, marble-look vanity with vessel basin and mirrored cabinets.' },
            { src: '/images/models/mirage-cafe/interior-09.jpg', caption: 'Private queen bedroom — quilted mattress, overhead cabinetry, bedside shelves with reading lights on both sides.' },
            { src: '/images/models/mirage-cafe/interior-10.jpg', caption: 'Cafe dinette in detail — fixed stone-look table between padded bench seats, fridge column and entry door on the right.' },
            { src: '/images/models/mirage-cafe/interior-11.jpg', caption: 'Kitchen from the rear — gloss uppers, stone benchtop, 4-burner cooktop with oven and a glimpse of the bed beyond.' },
            { src: '/images/models/mirage-cafe/interior-12.jpg', caption: 'Ensuite detail — front-loading washer, marble-look vanity with vessel sink, mirror-fronted overhead cabinet.' },
          ],
        },
      },
      {
        key: 'recliners',
        label: 'Twin Recliners',
        shortLabel: 'Recliners',
        badge: 'Mirage · Recliner Lounge',
        blurb: 'Two individual reclining chairs with a shared side table — the relaxed evenings-in layout for couples.',
        blueprint: '/images/blueprints/mirage-recliners.webp',
        floorPlan: '/images/blueprints/mirage-20-6.png',
        sizes: DEFAULT_SIZES,
        floorPlansBySize: {
          '20-6': '/images/blueprints/mirage-20-6.png',
        },
        description:
          'The Recliner-layout Mirage swaps the fixed dinette for two individual reclining lounge chairs with a small shared side table. It\'s the evenings-in, movie-night layout — everyone gets their own seat, and there\'s nothing hard to knock a knee on. Everything else is the same Mirage you know: full galley, ensuite with laundry and a private rear queen bedroom.',
        features: [
          'Twin individual reclining lounge chairs with side table',
          'Relaxed, living-room feel — no shared bench seat',
          'Full kitchen — 4-burner cooktop with oven, stainless sink, stone-look bench',
          'Rear private queen bed with wrap-around storage',
          'Full ensuite with separate shower, cassette toilet and vanity',
          'Marble-look vanity top with matte black tapware',
          'Gloss white upper cabinetry and dark gloss lower drawers',
          'Dometic cassette air-conditioner and ceiling ventilation',
          'Twin gas-bottle mount, off-road-ready hitch and drawbar',
        ],
        specs: {
          sleeps: 'Up to 4',
          length: 'TBC',
          tare: 'TBC',
          atm: 'TBC',
          suspension: 'Standard independent',
          water: 'TBC',
          warranty: 'TBC',
        },
        gallery: {
          exterior: [
            { src: '/images/models/mirage-recliners/exterior-01.jpg', caption: 'Mirage 206 front — twin gas-bottle hitch, off-road drawbar, aerodynamic nose cone.' },
            { src: '/images/models/mirage-recliners/exterior-02.jpg', caption: 'Full side profile — single-axle on-road build, white body with charcoal and green graphics.' },
            { src: '/images/models/mirage-recliners/exterior-03.jpg', caption: 'Rear view — spare wheel, reflective tail strip, full stone-guard underbody.' },
          ],
          interior: [
            { src: '/images/models/mirage-recliners/interior-01.jpg', caption: 'Fridge / microwave column beside the ensuite entry — black appliances, gloss white cabinetry, wood-look flooring.' },
            { src: '/images/models/mirage-recliners/interior-02.jpg', caption: 'Galley looking into the lounge — Dometic cassette air-con overhead, gloss white uppers, dark drawers, a recliner chair just catching the edge of frame.' },
            { src: '/images/models/mirage-recliners/interior-03.jpg', caption: 'Twin recliner chairs with shared side-table — bucket seats, tall headrests, fridge tower and galley on the right.' },
          ],
        },
      },
      {
        key: 'queen-bed',
        label: 'Queen Bed Layout',
        shortLabel: 'Queen Bed',
        badge: 'Mirage · Queen Bed',
        blurb: 'Compact Mirage 166 built around a rear queen bed — a simple padded bench lounge keeps the floor plan tidy for couples.',
        blueprint: '/images/blueprints/mirage-queenbed.webp',
        floorPlan: '/images/blueprints/mirage-20-6.png',
        sizes: DEFAULT_SIZES,
        floorPlansBySize: {
          '16-6': '/images/blueprints/mirage-16-6.png',
          '18-6': '/images/blueprints/mirage-18-6.png',
          '20-6': '/images/blueprints/mirage-20-6.png',
        },
        description:
          'The Queen Bed Mirage is the compact couples\' floor plan. A full-size rear queen bed sits under gloss white overhead cabinetry with a padded headboard and reading lights on either side, and a simple cushioned bench lounge keeps the living area uncluttered. The full galley, ensuite with separate shower and twin-gas-bottle off-road hitch all stay — just in a shorter, lighter body that\'s easier to tow and park.',
        features: [
          'Rear private queen bed with padded headboard and reading lights',
          'Full-height bedside wardrobes and overhead cabinetry',
          'Padded bench lounge with overhead storage and side window',
          'Full kitchen — 4-burner cooktop with oven, stainless sink, stone-look bench',
          'Fridge / microwave column beside the ensuite entry',
          'Full ensuite with separate shower, cassette toilet and vanity',
          'Compact Mirage 166 body — easier to tow and easier to park',
          'Twin gas-bottle mount, off-road-ready hitch and checker-plate stone guard',
          'Dometic cassette air-conditioner and large awning windows',
        ],
        specs: {
          sleeps: 'Up to 2',
          length: 'TBC',
          tare: '2180 kg',
          gtm: '2626 kg',
          atm: '2800 kg',
          suspension: 'Standard independent',
          water: 'TBC',
          warranty: 'TBC',
        },
        gallery: {
          exterior: [
            { src: '/images/models/mirage-queenbed/exterior-01.jpg', caption: 'Mirage 166 front-on — twin gas-bottle hitch, off-road drawbar, checker-plate stone guard and Sahara Caravans branding.' },
            { src: '/images/models/mirage-queenbed/exterior-02.jpg', caption: 'Front-quarter view — nose-cone body, white upper panels with black checker-plate skirt along the underbody.' },
            { src: '/images/models/mirage-queenbed/exterior-03.jpg', caption: 'Front-quarter from the opposite side — aerodynamic profile, large side windows and oversized stone guard.' },
            { src: '/images/models/mirage-queenbed/exterior-04.jpg', caption: 'Full side profile — single-axle on-road build, checker-plate skirt and alloy wheel.' },
            { src: '/images/models/mirage-queenbed/exterior-05.jpg', caption: 'Kerb-side view — entry door and external service hatch to the front tunnel boot.' },
          ],
          interior: [
            { src: '/images/models/mirage-queenbed/interior-01.jpg', caption: 'Rear queen bed — quilted mattress, dark padded headboard, gloss white overhead cabinetry and reading lights on both sides.' },
            { src: '/images/models/mirage-queenbed/interior-02.jpg', caption: 'Padded bench lounge — cushioned seat-back, overhead cabinetry, awning window and power outlet panel within easy reach.' },
            { src: '/images/models/mirage-queenbed/interior-03.jpg', caption: 'Lounge from the entry — bench seating, side window and a glimpse of the galley just around the corner.' },
            { src: '/images/models/mirage-queenbed/interior-04.jpg', caption: 'Living area looking back to the bedroom — bench seat, overhead lockers and wood-look flooring through to the rear bed.' },
            { src: '/images/models/mirage-queenbed/interior-05.jpg', caption: 'Galley from the bedroom — gloss white uppers and lowers, under-bench oven with 4-burner cooktop and fridge / microwave tower.' },
            { src: '/images/models/mirage-queenbed/interior-06.jpg', caption: 'Full kitchen — stone-look bench, stainless sink, awning window above and fridge column alongside the ensuite.' },
            { src: '/images/models/mirage-queenbed/interior-07.jpg', caption: 'Kitchen in detail — 4-burner cooktop with oven below, deep drawer stack and utility cupboards under the bench.' },
            { src: '/images/models/mirage-queenbed/interior-08.jpg', caption: 'Ensuite — cassette toilet, gloss white cabinetry, wet-wall panels and marble-look vanity top.' },
            { src: '/images/models/mirage-queenbed/interior-09.jpg', caption: 'Separate shower stall — chrome hand-held, slide rail and slip-resistant base set in bright wet-wall.' },
            { src: '/images/models/mirage-queenbed/interior-10.jpg', caption: 'Vanity detail — marble-look top with vessel basin, mirror-fronted overhead cabinet and matte-black tapware.' },
          ],
        },
      },
      {
        key: 'single-bed',
        label: 'Single Bed Layout',
        shortLabel: 'Single Beds',
        badge: 'Mirage · Twin Singles',
        blurb: 'Compact Mirage 166 with two rear single beds split by a central cabinet — flexible for families, friends or gear.',
        blueprint: '/images/blueprints/mirage-singlebed.webp',
        sizes: DEFAULT_SIZES,
        floorPlansBySize: {
          '16-6': '/images/blueprints/mirage-singlebed-16-6.png',
        },
        description:
          'The Single Bed Mirage swaps the queen for two independent single beds at the rear, split by a central cabinet column with overhead storage and an oversized skylight above. It\'s the flexible layout — two friends who want their own space, parents sharing with a teenager, or anyone who needs the extra stowage the central column provides. The rest of the build stays true to the Mirage: full galley, ensuite with separate shower and a cushioned lounge in the living area.',
        features: [
          'Two rear single beds with quilted mattresses and overhead shelves',
          'Central cabinet column between the beds with storage and skylight above',
          'Cushioned lounge / bench seating in the main living area',
          'Full kitchen — 4-burner cooktop with oven, stainless sink, stone-look bench',
          'Fridge / microwave column with Dometic cassette air-conditioner overhead',
          'Full ensuite with separate shower, cassette toilet and vanity',
          'Compact Mirage 166 body — easier to tow and easier to park',
          'Twin gas-bottle mount, off-road-ready hitch and checker-plate stone guard',
          'Large awning windows each side of the bedroom for airflow',
        ],
        specs: {
          sleeps: 'Up to 2',
          length: 'TBC',
          tare: '2021 kg',
          gtm: '2600 kg',
          atm: '2750 kg',
          suspension: 'Standard independent',
          water: 'TBC',
          warranty: 'TBC',
        },
        gallery: {
          exterior: [
            { src: '/images/models/mirage-singlebed/exterior-01.jpg', caption: 'Mirage 166 kerb side on gravel — green and charcoal graphics, oversized windows, checker-plate stone guard and single-axle alloy wheel.' },
            { src: '/images/models/mirage-singlebed/exterior-02.jpg', caption: 'Full front view — twin gas bottles on the off-road drawbar, nose-cone body and bright white upper panels.' },
            { src: '/images/models/mirage-singlebed/exterior-03.jpg', caption: 'Full side profile — checker-plate skirt along the length, awning bar and entry step folded down.' },
            { src: '/images/models/mirage-singlebed/exterior-04.jpg', caption: 'Front-quarter detail — SW66 suspension badge, stone guard and reflective strip along the underbody.' },
            { src: '/images/models/mirage-singlebed/exterior-05.jpg', caption: 'Off-side view — rear corner with reflective tail strip and full stone-guard skirt.' },
          ],
          interior: [
            { src: '/images/models/mirage-singlebed/interior-01.jpg', caption: 'Twin single beds at the rear — quilted mattresses, central cabinet column with overhead shelves, skylight above and large awning windows on both sides.' },
            { src: '/images/models/mirage-singlebed/interior-02.jpg', caption: 'Single beds from the lounge — wood-look flooring, gloss white cabinetry and the edge of the galley just in frame.' },
            { src: '/images/models/mirage-singlebed/interior-03.jpg', caption: 'Lounge area — padded bench seat with cushioned back, overhead lockers and awning window onto the outside.' },
            { src: '/images/models/mirage-singlebed/interior-04.jpg', caption: 'Living area — cushioned bench, gloss white overhead storage, wood-look flooring and view through to the bedroom.' },
            { src: '/images/models/mirage-singlebed/interior-05.jpg', caption: 'Lounge looking forward — padded seating, side window and TV mount in the corner.' },
            { src: '/images/models/mirage-singlebed/interior-06.jpg', caption: 'Galley looking back to the beds — Dometic cassette air-con overhead, gloss white uppers, under-bench oven, fridge / microwave tower and entry to the ensuite.' },
            { src: '/images/models/mirage-singlebed/interior-07.jpg', caption: 'Fridge column beside the ensuite — black 3-way fridge with microwave on top, gloss white cabinetry and wood-look flooring.' },
            { src: '/images/models/mirage-singlebed/interior-08.jpg', caption: 'Ensuite — cassette toilet and shower stall, gloss white cabinetry and wet-wall panels.' },
            { src: '/images/models/mirage-singlebed/interior-09.jpg', caption: 'Ensuite in use — vanity with marble-look top, mirror-fronted overhead cabinet and matte-black tapware.' },
            { src: '/images/models/mirage-singlebed/interior-10.jpg', caption: 'Separate shower stall — chrome hand-held, slide rail and bright wet-wall panels.' },
            { src: '/images/models/mirage-singlebed/interior-11.jpg', caption: 'Cassette toilet — full-height wet-wall panels, compact footprint alongside the vanity.' },
          ],
        },
      },
    ],
  },
  {
    slug: 'dune',
    name: 'Sahara Dune',
    type: 'Semi-Off-Road',
    order: 3,
    tagline: 'Adventure and comfort in balance.',
    description:
      'The Dune is a free-camping tourer built for the long way around. An Australian-made 3.2mm super-gal chassis sits over 3.3-tonne independent coil-spring trailing-arm suspension, 235/75R15 off-road rims and 10" electric brakes. 420W of solar feeds 270Ah of lithium, so you can stay out for weeks — and inside, a queen bed, café dinette and full ensuite with one-piece shower, toilet and gas/electric hot water keep things comfortable wherever you stop.',
    heroImage: '/images/hero/hero-dune.png',
    gallery: [
      '/images/models/dune/gallery-1.png',
      '/images/models/dune/gallery-2.png',
      '/images/models/dune/gallery-3.png',
      '/images/models/dune/gallery-4.png',
    ],
    features: [
      '3.3-tonne independent coil-spring trailing-arm suspension',
      'DO35 off-road coupling with 6" A-frame and 4" raiser',
      '235/75R15 off-road rims and tyres with 10" electric brakes',
      'Australian-made 3.2mm super-gal chassis (Australian steel)',
      '3-bar rear bumper, jerry-can holder and A-frame toolbox',
      'Galvanised generator locker and tunnel boot',
      'Pro-Bond aluminium composite body with checker-plate front, rear and sides',
      'Double-glazed windows throughout',
      'Roll-out awning with centre support and twin awning lights',
      'Reverse camera plus front and rear work lights',
      '420W solar (2 x 210W) feeding 270Ah of lithium (2 x 135Ah)',
      'BMPro battery management system with MPPT solar regulator',
      'Twin 9kg gas bottles',
      '12V points at all bed sides',
      'Dometic 190L 3-way fridge',
      'Recessed cooktop with grill — 3 gas burners and 1 electric',
      'Microwave with full-height splashbacks',
      'Swift gas/electric hot water service — Australian-made stainless steel',
      'Water filter tap at sink',
      'One-piece shower and toilet',
      'Queen bed 6\'5" x 5\'2" — inner-spring mattress with pillow top',
      'Gas-strut lift bed for under-bed storage',
      'Café seating with folding table',
      'LED lighting throughout',
      '24" LCD/DVD TV with CD/Radio and Winegard antenna (Sensar FreeVision)',
      '2 x external speakers and a 240V picnic-table point',
      'Piano hinges and gas struts on all overhead cupboards',
      'Pullout alloy step',
    ],
    specs: {
      sleeps: 'Up to 4',
      length: '20\'6"',
      tare: 'TBC',
      atm: 'TBC',
      suspension: '3.3T independent coil-spring trailing arm',
      water: '190L (2 x 95L)',
      warranty: '3 years structural',
    },
    highlights: ['Toilet', 'Shower', 'Kitchenette', 'Off-Grid'],
    ctaLabel: 'Enquire about the Dune',
    sizes: DEFAULT_SIZES,
    floorPlansBySize: {},
    technicalSpecs: [
      {
        id: 'chassis',
        label: 'Chassis',
        rows: [
          { label: 'Main Chassis Frame', value: '3.2mm super-gal — Australian made, Australian steel' },
          { label: 'A-Frame', value: '6"' },
          { label: 'Raiser', value: '4"' },
          { label: 'Suspension', value: '3.3T independent coil-spring trailing arm' },
          { label: 'Trailer Coupling', value: 'DO35 off-road coupling' },
          { label: 'Rims & Tyres', value: '235/75R15 off-road' },
          { label: 'Brakes', value: '10" electric' },
          { label: 'Rear Bumper', value: '3-bar' },
          { label: 'Jerry Can Holder', value: '1' },
          { label: 'A-Frame Toolbox', value: 'Included' },
          { label: 'Tank Protection', value: 'Galvanised sheet under tanks' },
        ],
      },
      {
        id: 'solar-power',
        label: 'Solar & Power',
        rows: [
          { label: 'Solar Panels', value: '2 x 210W (420W total)' },
          { label: 'Lithium Batteries', value: '2 x 135Ah (270Ah total)' },
          { label: 'Battery Management', value: 'BMPro' },
          { label: 'Solar Regulator', value: 'MPPT' },
          { label: '12V Points at Bedsides', value: 'Included' },
        ],
      },
      {
        id: 'electrical',
        label: 'Electrical',
        rows: [
          { label: 'LED Lighting Throughout', value: 'Included' },
          { label: 'LCD/DVD TV', value: '24"' },
          { label: 'Sound System', value: 'CD/Radio' },
          { label: 'TV Antenna', value: 'Winegard with Sensar FreeVision' },
          { label: 'External Speakers', value: '2' },
          { label: 'Awning Lights', value: 'Twin' },
          { label: 'Work Lights', value: 'Front and rear' },
          { label: 'Reverse Camera', value: 'Included' },
        ],
      },
      {
        id: 'plumbing',
        label: 'Plumbing',
        rows: [
          { label: 'Fresh Water Tanks', value: '2 x 95L' },
          { label: 'Grey Water Tank', value: 'Included' },
          { label: 'Hot Water Service', value: 'Swift gas/electric — Australian-made stainless steel' },
          { label: 'Filtered Drinking Water Tap', value: 'Included' },
          { label: 'Gas Bottles', value: '2 x 9kg' },
        ],
      },
      {
        id: 'appliances',
        label: 'Appliances',
        rows: [
          { label: 'Fridge', value: 'Dometic 190L 3-way' },
          { label: 'Cooktop', value: 'Recessed with grill — 3 gas burners + 1 electric' },
          { label: 'Microwave', value: 'Included' },
        ],
      },
      {
        id: 'external',
        label: 'External',
        rows: [
          { label: 'Body Cladding', value: 'Pro-Bond aluminium composite' },
          { label: 'Checker Plate', value: 'Front, rear and sides' },
          { label: 'Tunnel Boot', value: 'Included' },
          { label: 'Gas Bayonet', value: 'Included' },
          { label: 'Awning', value: 'Roll-out with centre support' },
          { label: 'Picnic Table', value: 'With 240V point' },
          { label: 'Double Glazed Windows', value: 'Included' },
          { label: 'Generator Locker', value: 'Galvanised' },
          { label: 'Entrance Step', value: 'Pullout alloy' },
        ],
      },
      {
        id: 'internal',
        label: 'Internal',
        rows: [
          { label: 'Queen Bed', value: '6\'5" x 5\'2" — inner spring with pillow top' },
          { label: 'Bed Lift', value: 'Gas strut' },
          { label: 'Seating', value: 'Café with folding table' },
          { label: 'Splashbacks', value: 'Full height' },
          { label: 'Cupboard Hinges', value: 'Piano hinges throughout' },
          { label: 'Overhead Cupboards', value: 'Gas struts' },
          { label: 'Shower', value: 'One-piece' },
          { label: 'Toilet', value: 'Included' },
        ],
      },
    ],
  },
  {
    slug: 'horizon',
    name: 'Sahara Horizon',
    type: 'Family',
    order: 4,
    tagline: 'Making memories — wherever the road takes you.',
    description:
      'The Horizon is the family van — a 22\'8" body laid out to sleep six, with a private rear queen, four full-length bunks behind a concertina door and an L-lounge in the middle. Built on a hybrid frame (Celuka front sheeting, Meranti elsewhere, honeycomb floor and a one-piece aluminium roof), it pairs a 200L Dometic 2-way fridge/freezer, top-load washing machine and reverse-cycle air-con with 420W of solar feeding 300Ah of lithium — set up for proper free camps without leaving any of the family comforts behind.',
    heroImage: '/images/hero/hero-horizon.png',
    gallery: ['/images/models/horizon/hero.png'],
    features: [
      'Hybrid frame — Celuka front sheeting, Meranti remaining frame, one-piece aluminium roof',
      'One-piece honeycomb floor',
      'Australian-made 3.2mm super-gal chassis (Australian steel)',
      'Load-sharing suspension with 2" chassis raiser',
      '15" rims with 235/75R15 tyres and 10" electric brakes',
      '3.5T ball coupling and 6" A-frame',
      '3-bar rear galvanised bumper and quick-drop corner stands',
      'Aluminium A-frame toolbox with 2 x 9kg gas bottles on slide-out',
      'Pro-Bond aluminium composite body with checker-plate front, rear and sides',
      'AllyTech double-glazed windows and 2 x skylight hatches',
      'Round-top entry door with alloy step',
      'Roll-out awning with centre support and twin awning lights',
      'Tunnel boot with internal lighting',
      'External entertainment hatch with TV point and 12V power',
      '2 x external speakers and external picnic table',
      'Reverse camera',
      '420W solar (2 x 210W) feeding a 300Ah lithium battery',
      'Projecta battery management system',
      'Dometic Fresh Jet Pro reverse-cycle air conditioner',
      'Dometic 200L 2-way fridge/freezer (12V/240V compressor)',
      'Microwave with full-height kitchen splashbacks',
      'Stainless steel sink with filtered drinking-water tap',
      'Swift gas/electric hot water service plus Suburban continuous hot water',
      'L-lounge with adjustable table leg',
      'One-piece shower and china-bowl toilet (separate)',
      'Top-load washing machine',
      'Private rear queen bed 6\'5" x 5\' — inner-spring mattress with pillow top',
      'Gas-strut posture slat bed base for under-bed storage',
      'Four full-length bunks (6\'2") with concertina door',
      '12V fan in bedroom and one in each bunk (4 in bunks)',
      'USB, USB-C and 240V points at bunks and in robe nooks',
      '24" LCD TV with Bluetooth/Radio audio and Winegard antenna (Sensar FreeVision)',
      'LED strip lighting in overhead cupboards and LED lighting throughout',
      'Piano hinges and gas struts on all overhead cupboards',
    ],
    specs: {
      sleeps: 'Up to 6',
      length: '22\'8"',
      tare: 'TBC',
      atm: 'TBC',
      suspension: 'Load-sharing',
      water: '190L (2 x 95L)',
      warranty: 'TBC',
    },
    highlights: ['Toilet', 'Shower', 'Laundry', 'Kitchenette', 'Bunks'],
    ctaLabel: 'Enquire about the Horizon',
    sizes: ['19-6', '20-6', '21-6', '22-6'],
    floorPlansBySize: {},
    technicalSpecs: [
      {
        id: 'chassis',
        label: 'Chassis',
        rows: [
          { label: 'Main Chassis Frame', value: '3.2mm super-gal — Australian made, Australian steel' },
          { label: 'A-Frame', value: '6"' },
          { label: 'Raiser', value: '2"' },
          { label: 'Suspension', value: 'Load-sharing' },
          { label: 'Trailer Coupling', value: '3.5T ball coupling' },
          { label: 'Rims & Tyres', value: '15" rims with 235/75R15' },
          { label: 'Brakes', value: '10" electric' },
          { label: 'Rear Bumper', value: '3-bar galvanised' },
          { label: 'Corner Stands', value: 'Quick drop' },
          { label: 'A-Frame Toolbox', value: 'Aluminium with 2 x 9kg gas bottles on slide-out' },
          { label: 'Tank Protection', value: 'Galvanised sheet under tanks' },
          { label: 'Drawbar Tap', value: 'Included' },
        ],
      },
      {
        id: 'solar-power',
        label: 'Solar & Power',
        rows: [
          { label: 'Solar Panels', value: '2 x 210W (420W total)' },
          { label: 'Lithium Battery', value: '300Ah' },
          { label: 'Battery Management', value: 'Projecta' },
          { label: '12V/USB/USB-C Points', value: 'Robe nooks and bunks' },
          { label: '240V Power Points', value: 'Throughout' },
        ],
      },
      {
        id: 'electrical',
        label: 'Electrical',
        rows: [
          { label: 'LED Lighting Throughout', value: 'Included' },
          { label: 'LED Strip Lighting in Overhead Cupboards', value: 'Kitchen and seating area' },
          { label: 'LCD TV', value: '24"' },
          { label: 'Sound System', value: 'Bluetooth/Radio/Audio' },
          { label: 'TV Antenna', value: 'Winegard with Sensar FreeVision' },
          { label: 'External Entertainment Hatch', value: 'TV point and 12V power' },
          { label: 'External Speakers', value: '2' },
          { label: 'Awning Lights', value: 'Twin' },
          { label: 'Reverse Camera', value: 'Included' },
          { label: '12V Fans', value: '1 in bedroom, 1 in each bunk (4 in bunks)' },
        ],
      },
      {
        id: 'plumbing',
        label: 'Plumbing',
        rows: [
          { label: 'Fresh Water Tanks', value: '2 x 95L' },
          { label: 'Hot Water Service', value: 'Swift gas/electric — Australian-made stainless steel' },
          { label: 'Continuous Hot Water', value: 'Suburban' },
          { label: 'Stainless Steel Sink', value: 'Included' },
          { label: 'Filtered Drinking Water Tap', value: 'Included' },
          { label: 'Drawbar Tap', value: 'Included' },
          { label: 'Gas Bottles', value: '2 x 9kg' },
        ],
      },
      {
        id: 'appliances',
        label: 'Appliances',
        rows: [
          { label: 'Fridge/Freezer', value: 'Dometic 200L 2-way (12V/240V compressor)' },
          { label: 'Microwave', value: 'Included' },
          { label: 'Washing Machine', value: 'Top load' },
          { label: 'Air Conditioner', value: 'Dometic Fresh Jet Pro reverse-cycle' },
        ],
      },
      {
        id: 'external',
        label: 'External',
        rows: [
          { label: 'Body Cladding', value: 'Pro-Bond aluminium composite' },
          { label: 'Checker Plate', value: 'Front, rear and sides' },
          { label: 'Windows', value: 'AllyTech double-glazed' },
          { label: 'Skylight Hatches', value: '2' },
          { label: 'Tunnel Boot', value: 'With internal lighting' },
          { label: 'Gas Bayonet', value: 'Included' },
          { label: 'Awning', value: 'Roll-out with centre support' },
          { label: 'External Picnic Table', value: 'Included' },
          { label: 'Entry Door', value: 'Round top' },
          { label: 'Entrance Step', value: 'Alloy' },
        ],
      },
      {
        id: 'internal',
        label: 'Internal',
        rows: [
          { label: 'Construction', value: 'Hybrid frame — Celuka front, Meranti remaining, honeycomb floor, one-piece aluminium roof' },
          { label: 'Master Bed', value: 'Queen 6\'5" x 5\' — inner spring with pillow top' },
          { label: 'Bed Lift', value: 'Gas-strut posture slat base' },
          { label: 'Bunks', value: '4 x 6\'2" twin bunks with concertina door' },
          { label: 'Bunk Connectivity', value: 'USB, USB-C and 240V points' },
          { label: 'Robe Nooks', value: '12V USB, USB-C and 240V points' },
          { label: 'Lounge', value: 'L-lounge with adjustable table leg' },
          { label: 'Kitchen Splashbacks', value: 'Full height' },
          { label: 'Cupboard Hinges', value: 'Piano hinges throughout' },
          { label: 'Overhead Cupboards', value: 'Gas struts' },
          { label: 'Shower', value: 'One-piece (separate)' },
          { label: 'Toilet', value: 'China bowl (separate)' },
        ],
      },
    ],
  },
]

export function getModelBySlug(slug) {
  return models.find((m) => m.slug === slug)
}

export function getPrimaryVariant(model) {
  return model?.variants?.[0] ?? null
}

export function getVariantByKey(model, key) {
  if (!model?.variants) return null
  return model.variants.find((v) => v.key === key) ?? model.variants[0]
}

// Normalise a single-variant model's legacy `gallery: string[]` into the
// variant-aware `{ exterior, interior }` shape so the ModelPage only needs one
// rendering path.
export function normaliseGallery(model) {
  if (!model) return { exterior: [], interior: [] }
  if (Array.isArray(model.gallery)) {
    return {
      exterior: [],
      interior: model.gallery.map((src) => ({ src, caption: '' })),
    }
  }
  return model.gallery ?? { exterior: [], interior: [] }
}
